# Generated by Django 4.1.7 on 2023-03-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
