# Generated by Django 4.1.7 on 2023-03-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_ckeditor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ckEditor',
            new_name='MyModel',
        ),
    ]
