# Generated by Django 4.1.7 on 2023-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_ckeditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ckEditor',
        ),
    ]
